/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasFixasRouteImport } from './routes/_authenticated/contas-fixas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedMinhaFamiliaRouteImport } from './routes/_authenticated/minha-familia'
import { Route as AuthenticatedPerfilFinanceiroRouteImport } from './routes/_authenticated/perfil-financeiro'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedBancosIndexRouteImport } from './routes/_authenticated/bancos.index'
import { Route as AuthenticatedBancosAccountIdRouteImport } from './routes/_authenticated/bancos.$accountId'
import { Route as AuthenticatedCartoesIndexRouteImport } from './routes/_authenticated/cartoes.index'
import { Route as AuthenticatedCartoesCardIdRouteImport } from './routes/_authenticated/cartoes.$cardId'
import { Route as AuthenticatedHistoricoIndexRouteImport } from './routes/_authenticated/historico.index'
import { Route as AuthenticatedMembroMemberIdRouteImport } from './routes/_authenticated/membro.$memberId'
import { Route as AuthenticatedCartoesFaturasImportIdRouteImport } from './routes/_authenticated/cartoes.faturas.$importId'
import { Route as AuthenticatedHistoricoAnoMesRouteImport } from './routes/_authenticated/historico.$ano.$mes'
import { Route as AuthenticatedBancosAccountIdExtratosRevisarRouteImport } from './routes/_authenticated/bancos_.$accountId.extratos.revisar'
import { Route as AuthenticatedHistoricoFecharAnoMesRouteImport } from './routes/_authenticated/historico.fechar.$ano.$mes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasFixasRoute =
  AuthenticatedContasFixasRouteImport.update({
    id: '/contas-fixas',
    path: '/contas-fixas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaFamiliaRoute =
  AuthenticatedMinhaFamiliaRouteImport.update({
    id: '/minha-familia',
    path: '/minha-familia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilFinanceiroRoute =
  AuthenticatedPerfilFinanceiroRouteImport.update({
    id: '/perfil-financeiro',
    path: '/perfil-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBancosIndexRoute =
  AuthenticatedBancosIndexRouteImport.update({
    id: '/bancos/',
    path: '/bancos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBancosAccountIdRoute =
  AuthenticatedBancosAccountIdRouteImport.update({
    id: '/bancos/$accountId',
    path: '/bancos/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartoesIndexRoute =
  AuthenticatedCartoesIndexRouteImport.update({
    id: '/cartoes/',
    path: '/cartoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartoesCardIdRoute =
  AuthenticatedCartoesCardIdRouteImport.update({
    id: '/cartoes/$cardId',
    path: '/cartoes/$cardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoIndexRoute =
  AuthenticatedHistoricoIndexRouteImport.update({
    id: '/historico/',
    path: '/historico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembroMemberIdRoute =
  AuthenticatedMembroMemberIdRouteImport.update({
    id: '/membro/$memberId',
    path: '/membro/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartoesFaturasImportIdRoute =
  AuthenticatedCartoesFaturasImportIdRouteImport.update({
    id: '/cartoes/faturas/$importId',
    path: '/cartoes/faturas/$importId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoAnoMesRoute =
  AuthenticatedHistoricoAnoMesRouteImport.update({
    id: '/historico/$ano/$mes',
    path: '/historico/$ano/$mes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBancosAccountIdExtratosRevisarRoute =
  AuthenticatedBancosAccountIdExtratosRevisarRouteImport.update({
    id: '/bancos_/$accountId/extratos/revisar',
    path: '/bancos/$accountId/extratos/revisar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoFecharAnoMesRoute =
  AuthenticatedHistoricoFecharAnoMesRouteImport.update({
    id: '/historico/fechar/$ano/$mes',
    path: '/historico/fechar/$ano/$mes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-fixas': typeof AuthenticatedContasFixasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/minha-familia': typeof AuthenticatedMinhaFamiliaRoute
  '/perfil-financeiro': typeof AuthenticatedPerfilFinanceiroRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/bancos/$accountId': typeof AuthenticatedBancosAccountIdRoute
  '/cartoes/$cardId': typeof AuthenticatedCartoesCardIdRoute
  '/membro/$memberId': typeof AuthenticatedMembroMemberIdRoute
  '/bancos/': typeof AuthenticatedBancosIndexRoute
  '/cartoes/': typeof AuthenticatedCartoesIndexRoute
  '/historico/': typeof AuthenticatedHistoricoIndexRoute
  '/cartoes/faturas/$importId': typeof AuthenticatedCartoesFaturasImportIdRoute
  '/historico/$ano/$mes': typeof AuthenticatedHistoricoAnoMesRoute
  '/bancos/$accountId/extratos/revisar': typeof AuthenticatedBancosAccountIdExtratosRevisarRoute
  '/historico/fechar/$ano/$mes': typeof AuthenticatedHistoricoFecharAnoMesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-fixas': typeof AuthenticatedContasFixasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/minha-familia': typeof AuthenticatedMinhaFamiliaRoute
  '/perfil-financeiro': typeof AuthenticatedPerfilFinanceiroRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/bancos/$accountId': typeof AuthenticatedBancosAccountIdRoute
  '/cartoes/$cardId': typeof AuthenticatedCartoesCardIdRoute
  '/membro/$memberId': typeof AuthenticatedMembroMemberIdRoute
  '/bancos': typeof AuthenticatedBancosIndexRoute
  '/cartoes': typeof AuthenticatedCartoesIndexRoute
  '/historico': typeof AuthenticatedHistoricoIndexRoute
  '/cartoes/faturas/$importId': typeof AuthenticatedCartoesFaturasImportIdRoute
  '/historico/$ano/$mes': typeof AuthenticatedHistoricoAnoMesRoute
  '/bancos/$accountId/extratos/revisar': typeof AuthenticatedBancosAccountIdExtratosRevisarRoute
  '/historico/fechar/$ano/$mes': typeof AuthenticatedHistoricoFecharAnoMesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas-fixas': typeof AuthenticatedContasFixasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/minha-familia': typeof AuthenticatedMinhaFamiliaRoute
  '/_authenticated/perfil-financeiro': typeof AuthenticatedPerfilFinanceiroRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/bancos/$accountId': typeof AuthenticatedBancosAccountIdRoute
  '/_authenticated/cartoes/$cardId': typeof AuthenticatedCartoesCardIdRoute
  '/_authenticated/membro/$memberId': typeof AuthenticatedMembroMemberIdRoute
  '/_authenticated/bancos/': typeof AuthenticatedBancosIndexRoute
  '/_authenticated/cartoes/': typeof AuthenticatedCartoesIndexRoute
  '/_authenticated/historico/': typeof AuthenticatedHistoricoIndexRoute
  '/_authenticated/cartoes/faturas/$importId': typeof AuthenticatedCartoesFaturasImportIdRoute
  '/_authenticated/historico/$ano/$mes': typeof AuthenticatedHistoricoAnoMesRoute
  '/_authenticated/bancos_/$accountId/extratos/revisar': typeof AuthenticatedBancosAccountIdExtratosRevisarRoute
  '/_authenticated/historico/fechar/$ano/$mes': typeof AuthenticatedHistoricoFecharAnoMesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/compras'
    | '/configuracoes'
    | '/contas-fixas'
    | '/dashboard'
    | '/despesas'
    | '/minha-familia'
    | '/perfil-financeiro'
    | '/planejamento'
    | '/receitas'
    | '/relatorios'
    | '/bancos/$accountId'
    | '/cartoes/$cardId'
    | '/membro/$memberId'
    | '/bancos/'
    | '/cartoes/'
    | '/historico/'
    | '/cartoes/faturas/$importId'
    | '/historico/$ano/$mes'
    | '/bancos/$accountId/extratos/revisar'
    | '/historico/fechar/$ano/$mes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/compras'
    | '/configuracoes'
    | '/contas-fixas'
    | '/dashboard'
    | '/despesas'
    | '/minha-familia'
    | '/perfil-financeiro'
    | '/planejamento'
    | '/receitas'
    | '/relatorios'
    | '/bancos/$accountId'
    | '/cartoes/$cardId'
    | '/membro/$memberId'
    | '/bancos'
    | '/cartoes'
    | '/historico'
    | '/cartoes/faturas/$importId'
    | '/historico/$ano/$mes'
    | '/bancos/$accountId/extratos/revisar'
    | '/historico/fechar/$ano/$mes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas-fixas'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas'
    | '/_authenticated/minha-familia'
    | '/_authenticated/perfil-financeiro'
    | '/_authenticated/planejamento'
    | '/_authenticated/receitas'
    | '/_authenticated/relatorios'
    | '/_authenticated/bancos/$accountId'
    | '/_authenticated/cartoes/$cardId'
    | '/_authenticated/membro/$memberId'
    | '/_authenticated/bancos/'
    | '/_authenticated/cartoes/'
    | '/_authenticated/historico/'
    | '/_authenticated/cartoes/faturas/$importId'
    | '/_authenticated/historico/$ano/$mes'
    | '/_authenticated/bancos_/$accountId/extratos/revisar'
    | '/_authenticated/historico/fechar/$ano/$mes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-fixas': {
      id: '/_authenticated/contas-fixas'
      path: '/contas-fixas'
      fullPath: '/contas-fixas'
      preLoaderRoute: typeof AuthenticatedContasFixasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-familia': {
      id: '/_authenticated/minha-familia'
      path: '/minha-familia'
      fullPath: '/minha-familia'
      preLoaderRoute: typeof AuthenticatedMinhaFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil-financeiro': {
      id: '/_authenticated/perfil-financeiro'
      path: '/perfil-financeiro'
      fullPath: '/perfil-financeiro'
      preLoaderRoute: typeof AuthenticatedPerfilFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bancos/': {
      id: '/_authenticated/bancos/'
      path: '/bancos'
      fullPath: '/bancos/'
      preLoaderRoute: typeof AuthenticatedBancosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bancos/$accountId': {
      id: '/_authenticated/bancos/$accountId'
      path: '/bancos/$accountId'
      fullPath: '/bancos/$accountId'
      preLoaderRoute: typeof AuthenticatedBancosAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes/': {
      id: '/_authenticated/cartoes/'
      path: '/cartoes'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof AuthenticatedCartoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes/$cardId': {
      id: '/_authenticated/cartoes/$cardId'
      path: '/cartoes/$cardId'
      fullPath: '/cartoes/$cardId'
      preLoaderRoute: typeof AuthenticatedCartoesCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/': {
      id: '/_authenticated/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof AuthenticatedHistoricoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membro/$memberId': {
      id: '/_authenticated/membro/$memberId'
      path: '/membro/$memberId'
      fullPath: '/membro/$memberId'
      preLoaderRoute: typeof AuthenticatedMembroMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes/faturas/$importId': {
      id: '/_authenticated/cartoes/faturas/$importId'
      path: '/cartoes/faturas/$importId'
      fullPath: '/cartoes/faturas/$importId'
      preLoaderRoute: typeof AuthenticatedCartoesFaturasImportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/$ano/$mes': {
      id: '/_authenticated/historico/$ano/$mes'
      path: '/historico/$ano/$mes'
      fullPath: '/historico/$ano/$mes'
      preLoaderRoute: typeof AuthenticatedHistoricoAnoMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bancos_/$accountId/extratos/revisar': {
      id: '/_authenticated/bancos_/$accountId/extratos/revisar'
      path: '/bancos/$accountId/extratos/revisar'
      fullPath: '/bancos/$accountId/extratos/revisar'
      preLoaderRoute: typeof AuthenticatedBancosAccountIdExtratosRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/fechar/$ano/$mes': {
      id: '/_authenticated/historico/fechar/$ano/$mes'
      path: '/historico/fechar/$ano/$mes'
      fullPath: '/historico/fechar/$ano/$mes'
      preLoaderRoute: typeof AuthenticatedHistoricoFecharAnoMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasFixasRoute: typeof AuthenticatedContasFixasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedMinhaFamiliaRoute: typeof AuthenticatedMinhaFamiliaRoute
  AuthenticatedPerfilFinanceiroRoute: typeof AuthenticatedPerfilFinanceiroRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedBancosAccountIdRoute: typeof AuthenticatedBancosAccountIdRoute
  AuthenticatedCartoesCardIdRoute: typeof AuthenticatedCartoesCardIdRoute
  AuthenticatedMembroMemberIdRoute: typeof AuthenticatedMembroMemberIdRoute
  AuthenticatedBancosIndexRoute: typeof AuthenticatedBancosIndexRoute
  AuthenticatedCartoesIndexRoute: typeof AuthenticatedCartoesIndexRoute
  AuthenticatedHistoricoIndexRoute: typeof AuthenticatedHistoricoIndexRoute
  AuthenticatedCartoesFaturasImportIdRoute: typeof AuthenticatedCartoesFaturasImportIdRoute
  AuthenticatedHistoricoAnoMesRoute: typeof AuthenticatedHistoricoAnoMesRoute
  AuthenticatedBancosAccountIdExtratosRevisarRoute: typeof AuthenticatedBancosAccountIdExtratosRevisarRoute
  AuthenticatedHistoricoFecharAnoMesRoute: typeof AuthenticatedHistoricoFecharAnoMesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasFixasRoute: AuthenticatedContasFixasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedMinhaFamiliaRoute: AuthenticatedMinhaFamiliaRoute,
  AuthenticatedPerfilFinanceiroRoute: AuthenticatedPerfilFinanceiroRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedBancosAccountIdRoute: AuthenticatedBancosAccountIdRoute,
  AuthenticatedCartoesCardIdRoute: AuthenticatedCartoesCardIdRoute,
  AuthenticatedMembroMemberIdRoute: AuthenticatedMembroMemberIdRoute,
  AuthenticatedBancosIndexRoute: AuthenticatedBancosIndexRoute,
  AuthenticatedCartoesIndexRoute: AuthenticatedCartoesIndexRoute,
  AuthenticatedHistoricoIndexRoute: AuthenticatedHistoricoIndexRoute,
  AuthenticatedCartoesFaturasImportIdRoute:
    AuthenticatedCartoesFaturasImportIdRoute,
  AuthenticatedHistoricoAnoMesRoute: AuthenticatedHistoricoAnoMesRoute,
  AuthenticatedBancosAccountIdExtratosRevisarRoute:
    AuthenticatedBancosAccountIdExtratosRevisarRoute,
  AuthenticatedHistoricoFecharAnoMesRoute:
    AuthenticatedHistoricoFecharAnoMesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
