ALTER TYPE public.purchase_type ADD VALUE IF NOT EXISTS 'COMPRA_NORMAL';
ALTER TYPE public.purchase_type ADD VALUE IF NOT EXISTS 'COMPRA_RECORRENTE';
ALTER TYPE public.purchase_type ADD VALUE IF NOT EXISTS 'COMPRA_PARCELADA';
ALTER TYPE public.purchase_type ADD VALUE IF NOT EXISTS 'CONTA_RECORRENTE';