import { parseItau } from "@/lib/card-statement-parsers/itau";
import { itau004PdfLines, ITAU_004_SUBTOTAL_8294 } from "@/lib/card-statement-parsers/itau.regression.completude";

const r = parseItau(itau004PdfLines());
const f = (n:number)=>n.toFixed(2);
const b8294 = r.blocos?.find(b=>b.card_last4==="8294");
console.log("blocos", JSON.stringify(r.blocos,null,1));
console.log("subtotal oficial 8294", ITAU_004_SUBTOTAL_8294);
const total = r.entries.reduce((s,e)=>s+e.valor,0);
console.log("qtd itens", r.entries.length, "total", f(total));
const por = (t:string)=>r.entries.filter(e=>e.tipo_sugerido===t);
console.log("compras", por("COMPRA").length, f(por("COMPRA").reduce((s,e)=>s+e.valor,0)));
console.log("taxas", por("TAXA").length, f(por("TAXA").reduce((s,e)=>s+e.valor,0)));
console.log("estornos", por("ESTORNO").length, f(por("ESTORNO").reduce((s,e)=>s+e.valor,0)));
console.log("parcelas", r.entries.filter(e=>e.parcela_atual).length);
console.log("rejeitadas", r.rejeitadas?.length);
const motivos: Record<string,number> = {};
for (const x of r.rejeitadas ?? []) motivos[x.motivo]=(motivos[x.motivo]??0)+1;
console.log(motivos);
console.log("rejeitadas com data+valor:", (r.rejeitadas??[]).filter(x=>/^\d{2}\/\d{2}/.test(x.texto)).map(x=>x.texto+" | "+x.motivo));
console.log("diferenca fatura", f(6577.67-total));
